proto_outdir = "./managed_proto"

[[dependencies]]
  target = "github.com/protocolbuffers/protobuf/src/google/protobuf"
  branch = "main"
  path = "google/protobuf"

[[dependencies]]
  target = "github.com/googleapis/googleapis/google/bytestream"
  branch = "master"
  path = "google/bytestream"

[[dependencies]]
  target = "github.com/googleapis/googleapis/google/longrunning"
  branch = "master"
  path = "google/longrunning"

[[dependencies]]
  target = "github.com/googleapis/googleapis/google/rpc"
  branch = "master"
  path = "google/rpc"

[[dependencies]]
  target = "github.com/googleapis/googleapis/google/api"
  branch = "master"
  path = "google/api"

[[dependencies]]
  target = "github.com/googleapis/googleapis/google/devtools/build/v1"
  branch = "master"
  path = "google/devtools/build/v1"

[[dependencies]]
  target = "github.com/bazelbuild/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto"
  branch = "master"
  path = "build_event_stream"

[[dependencies]]
  target = "github.com/bazelbuild/bazel/src/main/protobuf"
  branch = "master"
  path = "src/main/protobuf"
  ignores = [
    "execution_graph.proto"
  ]

[[dependencies]]
  target = "github.com/bazelbuild/remote-apis/build/bazel"
  branch = "main"
  path = "build/bazel"
